//
//  GeneratedProgram.swift
//  phantomAI
//
//  Created by Ridwan Ali on 12/1/25.
//

import Foundation

/// Represents a program generated by the AI builder
/// This is the output from ProgramBuilderService
struct GeneratedProgram: Codable, Identifiable, Equatable {
    let id: String
    let name: String
    let description: String
    let workouts: [WorkoutPlan]
    let nutritionPlan: NutritionPlan
    let createdAt: Date
    
    struct WorkoutPlan: Codable, Identifiable, Equatable {
        let id: String
        let name: String
        let exercises: [Exercise]
        let scheduledDate: Date?
        
        struct Exercise: Codable, Identifiable, Equatable {
            let id: String
            let name: String
            let sets: Int
            let reps: Int?
            let weight: Double?
            let duration: TimeInterval?
        }
    }
    
    struct NutritionPlan: Codable, Equatable {
        let targetCalories: Int
        let proteinGrams: Int
        let carbGrams: Int
        let fatGrams: Int
        let mealSuggestions: [MealSuggestion]
        
        struct MealSuggestion: Codable, Identifiable, Equatable {
            let id: String
            let name: String
            let calories: Int
            let proteinGrams: Int
            let carbGrams: Int
            let fatGrams: Int
        }
    }
}

// MARK: - Conversion to Program

extension GeneratedProgram {
    /// Converts GeneratedProgram to the existing Program model
    func toProgram(userId: String) -> Program {
        Program(
            id: id,
            userId: userId,
            name: name,
            description: description,
            startDate: createdAt,
            endDate: nil,
            workouts: workouts.map { workout in
                Program.WorkoutPlan(
                    id: workout.id,
                    name: workout.name,
                    exercises: workout.exercises.map { exercise in
                        Program.Exercise(
                            id: exercise.id,
                            name: exercise.name,
                            sets: exercise.sets,
                            reps: exercise.reps,
                            weight: exercise.weight,
                            duration: exercise.duration
                        )
                    },
                    scheduledDate: workout.scheduledDate
                )
            },
            createdAt: createdAt
        )
    }
}

