//
//  GeneratedProgram.swift
//  phantomAI
//
//  Created by Ridwan Ali on 12/1/25.
//

import Foundation

/// Represents a program generated by the AI builder
/// This is the output from ProgramBuilderService
struct GeneratedProgram: Codable, Identifiable, Equatable {
    let id: String
    let name: String
    let description: String
    let workouts: [WorkoutPlan]
    let nutritionPlan: NutritionPlan
    let createdAt: Date
    
    struct WorkoutPlan: Codable, Identifiable, Equatable {
        let id: String
        let name: String
        let exercises: [Exercise]
        let scheduledDate: Date?
        
        struct Exercise: Codable, Identifiable, Equatable {
            let id: String
            let name: String
            let sets: Int
            let reps: Int?
            let weight: Double?
            let duration: TimeInterval?
        }
    }
    
    struct NutritionPlan: Codable, Equatable {
        let targetCalories: Int
        let proteinGrams: Int
        let carbGrams: Int
        let fatGrams: Int
        let mealSuggestions: [MealSuggestion]
        
        struct MealSuggestion: Codable, Identifiable, Equatable {
            let id: String
            let name: String
            let calories: Int
            let proteinGrams: Int
            let carbGrams: Int
            let fatGrams: Int
        }
    }
}

// MARK: - Placeholder Factory

extension GeneratedProgram {
    /// Creates a placeholder GeneratedProgram from a ProgramRequest
    static func placeholder(from request: ProgramRequest) -> GeneratedProgram {
        // Calculate calories using simple BMR + activity
        let bmr: Double
        switch request.sex {
        case .male:
            bmr = 10 * request.weightKg + 6.25 * request.heightCm - 5 * Double(request.age) + 5
        case .female:
            bmr = 10 * request.weightKg + 6.25 * request.heightCm - 5 * Double(request.age) - 161
        case .other:
            bmr = 10 * request.weightKg + 6.25 * request.heightCm - 5 * Double(request.age) - 78
        }
        
        let activityFactor: Double
        switch request.activityLevel {
        case .mostlySitting:
            activityFactor = 1.2
        case .sometimesOnFeet:
            activityFactor = 1.375
        case .oftenOnFeet:
            activityFactor = 1.55
        case .veryActive:
            activityFactor = 1.725
        }
        
        let maintenanceCalories = bmr * activityFactor
        let targetCalories: Int
        switch request.goal {
        case .loseFat:
            targetCalories = Int(maintenanceCalories - 400)
        case .buildMuscle, .getStronger:
            targetCalories = Int(maintenanceCalories + 200)
        default:
            targetCalories = Int(maintenanceCalories)
        }
        
        let proteinGrams = Int(request.weightKg * 2.0)
        let fatGrams = Int((Double(targetCalories) * 0.25) / 9.0)
        let carbGrams = Int((Double(targetCalories) - Double(proteinGrams) * 4 - Double(fatGrams) * 9) / 4.0)
        
        // Generate workout plans based on days per week
        let workoutPlans = (0..<request.daysPerWeek).map { index -> WorkoutPlan in
            let workoutNames = ["Upper Body", "Lower Body", "Full Body", "Push", "Pull", "Legs"]
            let workoutName = workoutNames[index % workoutNames.count]
            
            return WorkoutPlan(
                id: UUID().uuidString,
                name: workoutName,
                exercises: [
                    WorkoutPlan.Exercise(
                        id: UUID().uuidString,
                        name: "Exercise \(index + 1)",
                        sets: 3,
                        reps: 10,
                        weight: nil,
                        duration: nil
                    )
                ],
                scheduledDate: nil
            )
        }
        
        return GeneratedProgram(
            id: UUID().uuidString,
            name: "\(request.goal.title) Program",
            description: "A personalized program designed for your goals.",
            workouts: workoutPlans,
            nutritionPlan: NutritionPlan(
                targetCalories: max(1200, min(4000, targetCalories)),
                proteinGrams: proteinGrams,
                carbGrams: max(0, carbGrams),
                fatGrams: max(0, fatGrams),
                mealSuggestions: []
            ),
            createdAt: Date()
        )
    }
}

// MARK: - Conversion to Program

extension GeneratedProgram {
    /// Converts GeneratedProgram to the existing Program model
    func toProgram(userId: String) -> Program {
        Program(
            id: id,
            userId: userId,
            name: name,
            description: description,
            startDate: createdAt,
            endDate: nil,
            workouts: workouts.map { workout in
                Program.WorkoutPlan(
                    id: workout.id,
                    name: workout.name,
                    exercises: workout.exercises.map { exercise in
                        Program.Exercise(
                            id: exercise.id,
                            name: exercise.name,
                            sets: exercise.sets,
                            reps: exercise.reps,
                            weight: exercise.weight,
                            duration: exercise.duration
                        )
                    },
                    scheduledDate: workout.scheduledDate
                )
            },
            createdAt: createdAt
        )
    }
}

